name: Eslint check

on:
  pull_request:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Run npm install
        run: npm install
      - name: Run esLint
        run: npm run lint-check
