name: Publish

on:
  push:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: git
        run: |
          git --version
          git config --global user.name 'ginokok1996'
          git config --global user.email 'ginokok1996@users.noreply.github.com'
          git checkout development
      - run: npm install
      - run: npm version patch
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: git push && git push origin --tags