name: Publish

on:
  push:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: git
        run: |
          git --version
          git config user.name "GitHub Version patch"
          git config user.email "<>"
          git checkout development
      - name: Run npm install
        run: npm install
      - name: Update repository with new version
        run: npm version patch
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}